actualizado con mejoras en los ejercicios

diff --git a/ejercicios-shell-script/solucion/01-basicos/usuarioconectado b/ejercicios-shell-script/solucion/01-basicos/usuarioconectado
--- a/ejercicios-shell-script/solucion/01-basicos/usuarioconectado
+++ b/ejercicios-shell-script/solucion/01-basicos/usuarioconectado
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
 # script que retorna 
 #     un SI si el primer parámetro coincide con algún usuario conectado
 #     un NO en caso contrario
@@ -28,7 +32,7 @@ if [ $# -ne 1 ]; then
 	exit 1
 fi
 
-ESTA_CONECTADO=`who | grep $1`
+ESTA_CONECTADO=$(who | grep "$1")
 
 if [ -z "$ESTA_CONECTADO" ]; then
 	echo "NO"
diff --git a/ejercicios-shell-script/solucion/02-calculadora/division b/ejercicios-shell-script/solucion/02-calculadora/division
--- a/ejercicios-shell-script/solucion/02-calculadora/division
+++ b/ejercicios-shell-script/solucion/02-calculadora/division
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
 # script que divide dos números
 
 # función de ayuda
@@ -21,9 +25,9 @@ DESCRPCION_AYUDA
 
 function comprobarQueNoEsNumero() {
 
-	if [ -n "$1" \
-		-a "$1" != "0" \
-		-a "`echo $1 | awk '{ print $1*1 }'`" != "$1" ]; then
+	if [ -n "$1" ] \
+		&& [ "$1" != "0" ] \
+		&& [ "$(echo "$1" | awk '{ print $1*1 }')" != "$1" ]; then
 
 		echo "El parámetro '$1' no es un número"
 		ayuda
@@ -37,7 +41,7 @@ if [ $# -ne 2 ]; then
 	exit 1
 fi
 
-comprobarQueNoEsNumero $1
-comprobarQueNoEsNumero $2
+comprobarQueNoEsNumero "$1"
+comprobarQueNoEsNumero "$2"
 
-echo $1 $2 | awk '{ print $1 / $2 }'
+echo "$1" "$2" | awk '{ print $1 / $2 }'
diff --git a/ejercicios-shell-script/solucion/03-banco/banco b/ejercicios-shell-script/solucion/03-banco/banco
--- a/ejercicios-shell-script/solucion/03-banco/banco
+++ b/ejercicios-shell-script/solucion/03-banco/banco
@@ -1,6 +1,10 @@
 #! /bin/bash
 
-BANCO_FILE=~/.banco.txt
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
+BANCO_FILE="$HOME/.banco.txt"
 
 function help() {
 
@@ -32,43 +36,40 @@ DESCRIPCION_AYUDA
 
 function exitWithError() {
 
-    LINEA_ERROR=$1
-    MENSAJE_ERROR=$2
-    CODIGO_ERROR=$3
+    LINEA_ERROR="$1"
+    MENSAJE_ERROR="$2"
+    CODIGO_ERROR="$3"
 
-	echo "$0: línea $LINEA_ERRO: Error $CODIGO_ERROR: $MENSAJE_ERROR"
-	exit $CODIGO_ERROR
+	echo "$0: línea $LINEA_ERROR: Error $CODIGO_ERROR: $MENSAJE_ERROR"
+	exit "$CODIGO_ERROR"
 }
 
 function testDateExists() {
 
-    DATE=$1
+    DATE="$1"
 
     # si ya existe un movimiento bancario para la misma fecha
-    if [ -n "`grep -E ^$DATE $BANCO_FILE`" ]; then
+    if [ "$(grep -E "^$DATE" "$BANCO_FILE")" != "" ]; then
         exitWithError $LINENO "Ya existe un movimiento bancario para la fecha '$DATE'." 12
     fi
 }
 
 function testIsDate() {
 
-	DATE=$1
+	DATE="$1"
 
-	EXPRESION_CONCUERDA=`echo $DATE | grep -E \
-		^20[0-9]{2}-[01][0-9]-[0-3][0-9]$`
-
-	if [ -z "$EXPRESION_CONCUERDA" ]; then
+	if [ "$(echo "$DATE" | grep -E "^20[0-9]{2}-[01][0-9]-[0-3][0-9]$")" == "" ]; then
 		exitWithError $LINENO "'$DATE' no es una fecha" 4
 	fi
 }
 
-function testIsNubmer() {
+function testIsNumber() {
 
-	NUMBER=$1
+	NUMBER="$1"
 
-	if [ -n "$NUMBER" \
-	-a $NUMBER != "0" \
-	-a "`echo $NUMBER | awk '{ print $1*1 }'`" != "$NUMBER" ]; then
+	if [ -n "$NUMBER" ] \
+		&& [ "$NUMBER" != "0" ] \
+		&& [ "$(echo "$NUMBER" | awk '{ print $1*1 }')" != "$NUMBER" ]; then
 
 		exitWithError $LINENO "'$NUMBER' no es un número" 2
 	fi
@@ -76,57 +77,54 @@ function testIsNubmer() {
 
 function testParameterNumer() {
 
-	PARAMETER_NUMBER=$1
+	PARAMETER_NUMBER="$1"
 	shift
-	if [ $# -ne $PARAMETER_NUMBER ]; then
+	if [ $# -ne "$PARAMETER_NUMBER" ]; then
 		exitWithError $LINENO \
-		"Número de parámetros " \
-		"obligatorio: $PARAMETER_NUMBER" 3
+		"Número de parámetros obligatorio: $PARAMETER_NUMBER" 3
 	fi
 }
 
 function add() {
 
-	testParameterNumer 3 $@
+	testParameterNumer 3 "$@"
 
-	FECHA=$1
-	CONCEPTO=$2
-	CANTIDAD=$3
+	FECHA="$1"
+	CONCEPTO="$2"
+	CANTIDAD="$3"
 
-	testIsDate $FECHA
-	testDateExists $FECHA
-	testIsNubmer $CANTIDAD
+	testIsDate "$FECHA"
+	testDateExists "$FECHA"
+	testIsNumber "$CANTIDAD"
 
-	echo "$FECHA $CONCEPTO $CANTIDAD" >> $BANCO_FILE
+	echo "$FECHA $CONCEPTO $CANTIDAD" >> "$BANCO_FILE"
 }
 
 function search() {
 
-	testParameterNumer 1 $@
+	testParameterNumer 1 "$@"
 
-	PATRON=$1
+	PATRON="$1"
 
-	grep $PATRON $BANCO_FILE
+	grep "$PATRON" "$BANCO_FILE"
 }
 
 # lista movimientos ordenados por fecha
 function list() {
 
-	sort -nk 1 $BANCO_FILE
+	sort -nk 1 "$BANCO_FILE"
 }
 
 function total() {
 
-	awk '{s+=$3} END {print "Total="s}' $BANCO_FILE
+	awk '{s+=$3} END {print "Total="s}' "$BANCO_FILE"
 }
 
 function createFileIfNotExists() {
 
-	touch $BANCO_FILE
-	if [ "$?" != "0" ]; then
+	if ! touch "$BANCO_FILE"; then
 		exitWithError $LINENO \
-		"Error de entrada/salida en" \
-		"el fichero $BANCO_FILE" 5
+		"Error de entrada/salida en el fichero $BANCO_FILE" 5
 	fi
 }
 
@@ -134,8 +132,8 @@ function menu() {
 
 	case $1 in
 		-h|--help)		help;;
-		-a|--add)	    shift; 	add $@;;
-		-s|--search)	shift;	search $@;;
+		-a|--add)	    shift; 	add "$@";;
+		-s|--search)	shift;	search "$@";;
 		-l|--list)		list;;
 		-t|--total)		total;;
 		*) exitWithError $LINENO "Opción '$1' inválida." 1
@@ -145,7 +143,7 @@ function menu() {
 function init() {
 
 	createFileIfNotExists
-	menu $@
+	menu "$@"
 }
 
-init $@
+init "$@"
diff --git a/ejercicios-shell-script/solucion/04-demonios/alerta b/ejercicios-shell-script/solucion/04-demonios/alerta
--- a/ejercicios-shell-script/solucion/04-demonios/alerta
+++ b/ejercicios-shell-script/solucion/04-demonios/alerta
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
 # script que escribe la fecha en formato 'dd/mm/aaaa hh:mm:ss' cada X segundos
 # en el log '~/alerta.log'
 
@@ -16,7 +20,7 @@ DESCRIPCION_AYUDA
 }
 
 # si primer parámetro == '-h' o == '--help'
-if [ "$1" == "-h" -o "$1" == "--help" ]; then
+if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
     ayuda
     exit 0
 fi
@@ -26,7 +30,7 @@ function main() {
     DEFAULT=2
 
     # comprobar que SEGUNDOS es un número
-    if [ "$SEGUNDOS" != "0" -a "`echo $SEGUNDOS | awk '{ print $1 * 1 }'`" != "$SEGUNDOS" ]; then
+    if [ "$SEGUNDOS" != "0" ] && [ "$(echo "$SEGUNDOS" | awk '{ print $1 * 1 }')" != "$SEGUNDOS" ]; then
         echo "El parámetro '$1' no es un número. Se cogerá el valor por defecto ($DEFAULT)"
         SEGUNDOS=$DEFAULT
     fi
@@ -34,12 +38,12 @@ function main() {
     # reinicio alerta.log
     echo "" > ~/alerta.log
 
-    while [ true ]; do
+    while true; do
         date +%d/%m/%Y" "%H:%M:%S >> ~/alerta.log
         sleep $SEGUNDOS
     done
 }
 
-echo $$
+echo "$$"
 
-main $1
+main "$1"
diff --git a/ejercicios-shell-script/solucion/05-copias/copia-diferencial b/ejercicios-shell-script/solucion/05-copias/copia-diferencial
--- a/ejercicios-shell-script/solucion/05-copias/copia-diferencial
+++ b/ejercicios-shell-script/solucion/05-copias/copia-diferencial
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
 # script que empaqueta y comprime los ficheros modificados
 # desde la última copia-total
 # en un fichero llamado diferencial-aaaa.mm.dd-HH.MM.SS.tar.zip
@@ -9,49 +13,49 @@
 ############################################################
 
 # variable con la fecha en el formato indicado (aaaa.mm.dd-HH.MM.SS)
-FECHA=`date +%Y.%m.%d-%H.%M.%S`
+FECHA="$(date +%Y.%m.%d-%H.%M.%S)"
 
 # variable con la ruta de los ficheros
-RUTA_FICHEROS=~/copia_seguridad
+RUTA_FICHEROS="$HOME/copia_seguridad"
 
 # variable con el fichero con la fecha de la última copia total
-FICHERO_ULTIMA_COPIA_TOTAL=$RUTA_FICHEROS/fecha-ultima-copia-total.txt
+FICHERO_ULTIMA_COPIA_TOTAL="$RUTA_FICHEROS/fecha-ultima-copia-total.txt"
 
 # variable con el fichero con la fecha de la última copia diferencial
-FICHERO_ULTIMA_COPIA_DIFERENCIAL=$RUTA_FICHEROS/fecha-ultima-copia-diferencial.txt
+FICHERO_ULTIMA_COPIA_DIFERENCIAL="$RUTA_FICHEROS/fecha-ultima-copia-diferencial.txt"
 
 # variable con el fichero comprimido
-FICHERO_COMPRIMIDO=$RUTA_FICHEROS/diferencial-$FECHA.tar.zip
+FICHERO_COMPRIMIDO="$RUTA_FICHEROS/diferencial-$FECHA.tar.zip"
 
 # variable con eldirectorio que queremos copiar y comprimir
-DIRECTORIO_A_COPIAR=~/directorio_a_copiar
+DIRECTORIO_A_COPIAR="$HOME/directorio_a_copiar"
 
 ############################################################
 # FIN VARIABLES
 ############################################################
 
 # si no exixte el directorio a copiar mostramos un error y paramos la ejecución
-if [ ! -d $DIRECTORIO_A_COPIAR ]; then
+if [ ! -d "$DIRECTORIO_A_COPIAR" ]; then
 	echo "No exixte el directorio a copiar."
 	exit 1
 fi
 
 # si no existe el FICHERO_ULTIMA_COPIA_TOTAL mostramos un error
 # y paramos la ejecución
-if [ ! -e $FICHERO_ULTIMA_COPIA_TOTAL ]; then
+if [ ! -e "$FICHERO_ULTIMA_COPIA_TOTAL" ]; then
 	echo "No hay última copia total."
 	exit 1
 fi
 
 # si no exixte el directorio de los ficheros lo creamos
-if [ ! -d $RUTA_FICHEROS ]; then
-	mkdirs $RUTA_FICHEROS
+if [ ! -d "$RUTA_FICHEROS" ]; then
+	mkdirs "$RUTA_FICHEROS"
 fi
 
 # empaquetamos y comprimimos los ficheros modificados
 # desde la última copia total
-find $DIRECTORIO_A_COPIAR/* -newer $FICHERO_ULTIMA_COPIA_TOTAL | zip -@ $FICHERO_COMPRIMIDO
+find "$DIRECTORIO_A_COPIAR"/* -newer "$FICHERO_ULTIMA_COPIA_TOTAL" | zip -@ "$FICHERO_COMPRIMIDO"
 
 # guardar la fecha de la última copia diferencial
 # en FICHERO_ULTIMA_COPIA_DIFERENCIAL
-echo $FECHA > $FICHERO_ULTIMA_COPIA_DIFERENCIAL
+echo "$FECHA" > "$FICHERO_ULTIMA_COPIA_DIFERENCIAL"
diff --git a/ejercicios-shell-script/solucion/05-copias/copia-incremental b/ejercicios-shell-script/solucion/05-copias/copia-incremental
--- a/ejercicios-shell-script/solucion/05-copias/copia-incremental
+++ b/ejercicios-shell-script/solucion/05-copias/copia-incremental
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
 # script que empaqueta y comprime los ficheros modificados
 # desde la última copia incremental
 # en un fichero llamado incremental-aaaa.mm.dd-HH.MM.SS.tar.zip
@@ -9,19 +13,19 @@
 ############################################################
 
 # variable con la fecha en el formato indicado (aaaa.mm.dd-HH.MM.SS)
-FECHA=`date +%Y.%m.%d-%H.%M.%S`
+FECHA="$(date +%Y.%m.%d-%H.%M.%S)"
 
 # variable con la ruta de los ficheros
-RUTA_FICHEROS=~/copia_seguridad
+RUTA_FICHEROS="$HOME/copia_seguridad"
 
 # variable con el fichero con la fecha de la última copia incremental
-FICHERO_ULTIMA_COPIA_INCREMENTAL=$RUTA_FICHEROS/fecha-ultima-copia-incremental.txt
+FICHERO_ULTIMA_COPIA_INCREMENTAL="$RUTA_FICHEROS/fecha-ultima-copia-incremental.txt"
 
 # variable con el fichero comprimido
-FICHERO_COMPRIMIDO=$RUTA_FICHEROS/incremental-$FECHA.tar.zip
+FICHERO_COMPRIMIDO="$RUTA_FICHEROS/incremental-$FECHA.tar.zip"
 
 # variable con eldirectorio que queremos copiar y comprimir
-DIRECTORIO_A_COPIAR=~/directorio_a_copiar
+DIRECTORIO_A_COPIAR="$HOME/directorio_a_copiar"
 
 ############################################################
 # FIN VARIABLES
@@ -29,27 +33,27 @@ DIRECTORIO_A_COPIAR=~/directorio_a_copiar
 
 # si no exixte el directorio a copiar mostramos un error
 # y paramos la ejecución
-if [ ! -d $DIRECTORIO_A_COPIAR ]; then
+if [ ! -d "$DIRECTORIO_A_COPIAR" ]; then
 	echo "No exixte el directorio a copiar."
 	exit 1
 fi
 
 # si no existe el FICHERO_ULTIMA_COPIA_INCREMENTAL mostramos un error
 # y paramos la ejecución
-if [ ! -e $FICHERO_ULTIMA_COPIA_INCREMENTAL ]; then
+if [ ! -e "$FICHERO_ULTIMA_COPIA_INCREMENTAL" ]; then
 	echo "No hay última copia incremental."
 	exit 1
 fi
 
 # si no exixte el directorio de los ficheros lo creamos
-if [ ! -d $RUTA_FICHEROS ]; then
-	mkdirs $RUTA_FICHEROS
+if [ ! -d "$RUTA_FICHEROS" ]; then
+	mkdirs "$RUTA_FICHEROS"
 fi
 
 # empaqueta y comprime los ficheros modificados
 # desde la última copia incremental
-find $DIRECTORIO_A_COPIAR/*.txt -newer $FICHERO_ULTIMA_INCREMENTAL | zip -@ $FICHERO_COMPRIMIDO
+find "$DIRECTORIO_A_COPIAR"/*.txt -newer "$FICHERO_ULTIMA_INCREMENTAL" | zip -@ "$FICHERO_COMPRIMIDO"
 
 # guardar la fecha de la última copia incremental
 # en FICHERO_ULTIMA_COPIA_INCREMENTAL
-echo $FECHA > $FICHERO_ULTIMA_COPIA_INCREMENTAL
+echo "$FECHA" > "$FICHERO_ULTIMA_COPIA_INCREMENTAL"
diff --git a/ejercicios-shell-script/solucion/05-copias/copia-total b/ejercicios-shell-script/solucion/05-copias/copia-total
--- a/ejercicios-shell-script/solucion/05-copias/copia-total
+++ b/ejercicios-shell-script/solucion/05-copias/copia-total
@@ -1,23 +1,27 @@
 #! /bin/bash
 
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
 ############################################################
 # INICIO VARIABLES
 ############################################################
 
 # variable con la fecha en el formato indicado (aaaa.mm.dd-HH.MM.SS)
-FECHA=`date +%Y.%m.%d-%H.%M.%S`
+FECHA="$(date +%Y.%m.%d-%H.%M.%S)"
 
 # variable con la ruta de los ficheros
-RUTA_FICHEROS=~/copia_seguridad
+RUTA_FICHEROS="$HOME/copia_seguridad"
 
 # variable con el fichero con la fecha de la última copia total
-FICHERO_ULTIMA_COPIA_TOTAL=$RUTA_FICHEROS/fecha-ultima-copia-total.txt
+FICHERO_ULTIMA_COPIA_TOTAL="$RUTA_FICHEROS/fecha-ultima-copia-total.txt"
 
 # variable con el fichero comprimido
-FICHERO_COMPRIMIDO=$RUTA_FICHEROS/total-$FECHA.tar.zip
+FICHERO_COMPRIMIDO="$RUTA_FICHEROS/total-$FECHA.tar.zip"
 
 # variable con el directorio que queremos copiar y comprimir
-DIRECTORIO_A_COPIAR=~/directorio_a_copiar
+DIRECTORIO_A_COPIAR="$HOME/directorio_a_copiar"
 
 ############################################################
 # FIN VARIABLES
@@ -25,19 +29,19 @@ DIRECTORIO_A_COPIAR=~/directorio_a_copiar
 
 # si no exixte el directorio a copiar mostramos un error
 # y paramos la ejecución
-if [ ! -d $DIRECTORIO_A_COPIAR ]; then
+if [ ! -d "$DIRECTORIO_A_COPIAR" ]; then
 	echo "No exixte el directorio a copiar."
 	exit 1
 fi
 
 # si no exixte el directorio de los ficheros lo creamos
-if [ ! -d $RUTA_FICHEROS ]; then
-	mkdirs $RUTA_FICHEROS
+if [ ! -d "$RUTA_FICHEROS" ]; then
+	mkdirs "$RUTA_FICHEROS"
 fi
 
 # empaquetamos y comprimimos el DIRECTORIO_A_COPIAR
 # en FICHERO_COMPRIMIDO (mediante zip)
-zip -r $FICHERO_COMPRIMIDO $DIRECTORIO_A_COPIAR
+zip -r "$FICHERO_COMPRIMIDO" "$DIRECTORIO_A_COPIAR"
 
 # guardar la fecha de la última copia total en FICHERO_ULTIMA_COPIA_TOTAL
-echo $FECHA > $FICHERO_ULTIMA_COPIA_TOTAL
+echo "$FECHA" > "$FICHERO_ULTIMA_COPIA_TOTAL"
diff --git a/ejercicios-shell-script/solucion/06-varios/citas b/ejercicios-shell-script/solucion/06-varios/citas
--- a/ejercicios-shell-script/solucion/06-varios/citas
+++ b/ejercicios-shell-script/solucion/06-varios/citas
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
 # script que gestiona las citas de una consulta.
 
 # Para cada una de las opciones se comprobará que se introducen el número de parámetros correctos con el formato correcto.
@@ -49,34 +53,34 @@ function error() {
 	echo "$0: Línea $1: Error $3: $2"
 
 	# termina la ejecución del script con el codigo de retorno indicado
-	exit $3
+	exit "$3"
 }
 
 # función que comprueba el número de parámetros introducido
 #	$1 linea error
 #	$2 número de parámetros esperados
-#	$@ parámetros
+#	"$@" parámetros
 function numero_parametros() {
 
 	# líenea error
-	LINEA_ERROR=$1
+	LINEA_ERROR="$1"
 
 	# eliminamos el primer parámetro
 	shift
 
 	# número de parámetros esperados
-	NUMERO_PARAMETROS_ESPERADOS=$1
+	NUMERO_PARAMETROS_ESPERADOS="$1"
 
 	# volvemos a eliminar el primer parámetro
 	shift
 
 	# número de parámetros que nos queda
-	NUMERO_PARAMETROS_REALES=$#
+	NUMERO_PARAMETROS_REALES="$#"
 
 	# si el número de parámetros introducido es distinto del esperado
 	if [ "$NUMERO_PARAMETROS_REALES" != "$NUMERO_PARAMETROS_ESPERADOS" ]; then
 
-		error $LINEA_ERROR "Número de parámetros '$NUMERO_PARAMETROS_REALES' distinto de '$NUMERO_PARAMETROS_ESPERADOS'." 1
+		error "$LINEA_ERROR" "Número de parámetros '$NUMERO_PARAMETROS_REALES' distinto de '$NUMERO_PARAMETROS_ESPERADOS'." 1
 	fi
 }
 
@@ -86,21 +90,21 @@ function numero_parametros() {
 function formato_hora() {
 
 	# líenea error
-	LINEA_ERROR=$1
+	LINEA_ERROR="$1"
 
 	# recogemos la hora
-	HORA=$2
+	HORA="$2"
 
 	# si la hora introducida no es un número de 2 cifras
-	if [ -z "`echo $HORA | grep -E ^[0-9]{2}$`" ]; then
+	if [ -z "$(echo "$HORA" | grep -E "^[0-9]{2}$")" ]; then
 
-		error $LINEA_ERROR "La hora '$HORA' no es un número de 2 cifras." 2
+		error "$LINEA_ERROR" "La hora '$HORA' no es un número de 2 cifras." 2
 	fi
 
 	# si la hora no está comprendida entre 00 y 23
-	if [ $HORA -gt 23 ]; then
+	if [ "$HORA" -gt 23 ]; then
 
-		error $LINEA_ERROR "La hora '$HORA' no está comprendida entre 00 y 23" 2
+		error "$LINEA_ERROR" "La hora '$HORA' no está comprendida entre 00 y 23" 2
 	fi
 }
 
@@ -110,24 +114,24 @@ function formato_hora() {
 function solape_hora_inicial() {
 
 	# líenea error
-	LINEA_ERROR=$1
+	LINEA_ERROR="$1"
 
 	# recogemos la hora inicial
-	HORA_INICIAL=$2
+	HORA_INICIAL="$2"
 
 	# fichero con el programa awk
-	FICHERO_PROGRAMA_AWK=~/awk-program.txt
+	FICHERO_PROGRAMA_AWK="$HOME/awk-program.txt"
 
 	# sentencia awk para buscar si ya existe una cita que se solape
-	echo "{ if ( $HORA_INICIAL >= \$1 && $HORA_INICIAL < \$2 ) print \$0 }" > $FICHERO_PROGRAMA_AWK
+	echo "{ if ( $HORA_INICIAL >= \$1 && $HORA_INICIAL < \$2 ) print \$0 }" > "$FICHERO_PROGRAMA_AWK"
 
 	# ejecutamos el comando y guardamos el resultado en una variable
-	CITA_SOLAPADA=`more $CITAS_FILE | awk -f $FICHERO_PROGRAMA_AWK`
+	CITA_SOLAPADA=$(more "$CITAS_FILE" | awk -f "$FICHERO_PROGRAMA_AWK")
 
 	# si existe alguna cita que se solape
 	if [ -n "$CITA_SOLAPADA" ]; then
 
-		error $LINEA_ERROR "La hora inicial '$HORA_INICIAL' se solapa con la cita '$CITA_SOLAPADA'." 3
+		error "$LINEA_ERROR" "La hora inicial '$HORA_INICIAL' se solapa con la cita '$CITA_SOLAPADA'." 3
 	fi
 }
 
@@ -137,24 +141,24 @@ function solape_hora_inicial() {
 function solape_hora_final() {
 
 	# líenea error
-	LINEA_ERROR=$1
+	LINEA_ERROR="$1"
 
 	# recogemos la hora final
-	HORA_FINAL=$2
+	HORA_FINAL="$2"
 
 	# fichero con el programa awk
-	FICHERO_PROGRAMA_AWK=~/awk-program.txt
+	FICHERO_PROGRAMA_AWK="$HOME/awk-program.txt"
 
 	# sentencia awk para buscar si ya existe una cita que se solape
-	echo "{ if ( $HORA_FINAL > \$1 && $HORA_FINAL <= \$2 ) print \$0 }" > $FICHERO_PROGRAMA_AWK
+	echo "{ if ( $HORA_FINAL > \$1 && $HORA_FINAL <= \$2 ) print \$0 }" > "$FICHERO_PROGRAMA_AWK"
 
 	# ejecutamos el comando y guardamos el resultado en una variable
-	CITA_SOLAPADA=`more $CITAS_FILE | awk -f $FICHERO_PROGRAMA_AWK`
+	CITA_SOLAPADA=$(more "$CITAS_FILE" | awk -f "$FICHERO_PROGRAMA_AWK")
 
 	# si existe alguna cita que se solape
 	if [ -n "$CITA_SOLAPADA" ]; then
 
-		error $LINEA_ERROR "La hora final '$HORA_FINAL' se solapa con la cita '$CITA_SOLAPADA'." 3
+		error "$LINEA_ERROR" "La hora final '$HORA_FINAL' se solapa con la cita '$CITA_SOLAPADA'." 3
 	fi
 }
 
@@ -164,15 +168,15 @@ function solape_hora_final() {
 function nombre_paciente() {
 
 	# líenea error
-	LINEA_ERROR=$1
+	LINEA_ERROR="$1"
 
 	# recogemos el nombre del paciente
-	NOMBRE_PACIENTE=$2
+	NOMBRE_PACIENTE="$2"
 
 	# si el nombre ya está en el fichero de citas
-	if [ -n "`grep $NOMBRE_PACIENTE $CITAS_FILE`" ]; then
+	if [ -n "$(grep "$NOMBRE_PACIENTE" "$CITAS_FILE")" ]; then
 
-		error $LINEA_ERROR "Nombre del paciente '$NOMBRE_PACIENTE' repetido." 4
+		error "$LINEA_ERROR" "Nombre del paciente '$NOMBRE_PACIENTE' repetido." 4
 	fi
 }
 
@@ -181,12 +185,12 @@ function nombre_paciente() {
 function error_inexperado() {
 
 	# líenea error
-	LINEA_ERROR=$1
+	LINEA_ERROR="$1"
 
 	# si ocurre algún error inexperado
 	if [ "$?" != "0" ]; then
 
-		error $LINEA_ERROR "Error inexperado." 6
+		error "$LINEA_ERROR" "Error inexperado." 6
 	fi
 }
 
@@ -197,30 +201,30 @@ function error_inexperado() {
 function add() {
 
 	# comprobamos que el número de parámetros sea igual a 3
-	numero_parametros $LINENO 3 $@
+	numero_parametros $LINENO 3 "$@"
 
 	# inicializamos las variables con los valores de los parámetros introducidos
-	HORA_INICIAL=$1
-	HORA_FINAL=$2
+	HORA_INICIAL="$1"
+	HORA_FINAL="$2"
 	NOMBRE_PACIENTE=$3
 
 	# comprobamos que el formato de la hora inicial sea el correcto
-	formato_hora $LINENO $HORA_INICIAL
+	formato_hora $LINENO "$HORA_INICIAL"
 
 	# comprobamos que la hora inicial no se solape con alguna cita ya introducida
-	solape_hora_inicial $LINENO $HORA_INICIAL
+	solape_hora_inicial $LINENO "$HORA_INICIAL"
 
 	# comprobamos que el formato de la hora final sea el correcto
-	formato_hora $LINENO $HORA_FINAL
+	formato_hora $LINENO "$HORA_FINAL"
 
 	# comprobamos que la hora final no se solape con alguna cita ya introducida
-	solape_hora_final $LINENO $HORA_FINAL
+	solape_hora_final $LINENO "$HORA_FINAL"
 
 	# comprobamos que no exista ya el nombre del paciente
-	nombre_paciente $LINENO $NOMBRE_PACIENTE
+	nombre_paciente $LINENO "$NOMBRE_PACIENTE"
 
 	# grabamos al final del fichero
-	echo $HORA_INICIAL $HORA_FINAL $NOMBRE_PACIENTE >> $CITAS_FILE
+	echo "$HORA_INICIAL" "$HORA_FINAL" "$NOMBRE_PACIENTE" >> "$CITAS_FILE"
 
 	# comprobamos que no haya habido ningún error inexperado
 	error_inexperado $LINENO
@@ -231,12 +235,12 @@ function add() {
 function search() {
 
 	# comprobamos que el número de parámetros sea igual a 1
-	numero_parametros $LINENO 1 $@
+	numero_parametros $LINENO 1 "$@"
 
-	PATRON=$1
+	PATRON="$1"
 
 	# buscamos el patrón introducido en el fichero de las citas
-	grep $PATRON $CITAS_FILE
+	grep "$PATRON" "$CITAS_FILE"
 
 	# comprobamos que no haya habido ningún error inexperado
 	error_inexperado $LINENO
@@ -247,15 +251,15 @@ function search() {
 function init() {
 
 	# comprobamos que el número de parámetros sea igual a 1
-	numero_parametros $LINENO 1 $@
+	numero_parametros $LINENO 1 "$@"
 
-	HORA_INICIAL=$1
+	HORA_INICIAL="$1"
 
 	# comprobamos que el formato de la hora inicial sea el correcto
-	formato_hora $LINENO $HORA_INICIAL
+	formato_hora $LINENO "$HORA_INICIAL"
 
 	# buscamos la hora inicial en el fichero de las citas
-	grep -E ^$HORA_INICIAL.*$ $CITAS_FILE
+	grep -E "^$HORA_INICIAL.*$" $CITAS_FILE
 
 	# comprobamos que no haya habido ningún error inexperado
 	error_inexperado $LINENO
@@ -266,15 +270,15 @@ function init() {
 function end() {
 
 	# comprobamos que el número de parámetros sea igual a 1
-	numero_parametros $LINENO 1 $@
+	numero_parametros $LINENO 1 "$@"
 
-	HORA_FINAL=$1
+	HORA_FINAL="$1"
 
 	# comprobamos que el formato de la hora final sea el correcto
-	formato_hora $LINENO $HORA_FINAL
+	formato_hora "$LINENO" "$HORA_FINAL"
 
 	# buscamos la hora final en el fichero de las citas
-	grep -E ^...$HORA_FINAL.*$ $CITAS_FILE
+	grep -E "^...$HORA_FINAL.*$" "$CITAS_FILE"
 
 	# comprobamos que no haya habido ningún error inexperado
 	error_inexperado $LINENO
@@ -284,7 +288,7 @@ function end() {
 function name() {
 
 	# comprobamos que el número de parámetros sea igual a 0
-	numero_parametros $LINENO 0 $@
+	numero_parametros $LINENO 0 "$@"
 
 	# ordenamos el fichero de las citas por la tercera columna
 	sort -k 3 $CITAS_FILE
@@ -297,7 +301,7 @@ function name() {
 function hour() {
 
 	# comprobamos que el número de parámetros sea igual a 0
-	numero_parametros $LINENO 0 $@
+	numero_parametros $LINENO 0 "$@"
 
 	# ordenamos el fichero de las citas por la primera columna en formato numérico
 	sort -nk 1 $CITAS_FILE
@@ -313,7 +317,7 @@ touch $CITAS_FILE
 error_inexperado
 
 # recogemos la opción selecionada
-OPCION=$1
+OPCION="$1"
 
 # eliminamos el primer parámetro
 shift
@@ -321,11 +325,11 @@ shift
 # dependiendo de la opción seleccionada
 case $OPCION in
 	-h|--help)	    ayuda;;
-	-a|--add)	    add $@;;
-	-s|--search)	search $@;;
-	-i|--init)	    init $@;;
-	-e|--end)	    end $@;;
-	-n|--name)	    name $@;;
-	-o|--hour)	    hour $@;;
+	-a|--add)	    add "$@";;
+	-s|--search)	search "$@";;
+	-i|--init)	    init "$@";;
+	-e|--end)	    end "$@";;
+	-n|--name)	    name "$@";;
+	-o|--hour)	    hour "$@";;
 	*)		        error $LINENO "Opción '$OPCION' inválida." 5;;
 esac
diff --git a/ejercicios-shell-script/solucion/06-varios/elevado b/ejercicios-shell-script/solucion/06-varios/elevado
--- a/ejercicios-shell-script/solucion/06-varios/elevado
+++ b/ejercicios-shell-script/solucion/06-varios/elevado
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+set -o errexit  # the script ends if a command fails
+set -o pipefail # the script ends if a command fails in a pipe
+set -o nounset  # the script ends if it uses an undeclared variable
+
 # si el número de parámetros es distinto de 2
 if [ $# -ne 2 ]; then
 	echo "Para ejecutar este script se necesitan 2 números."
